AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Feedback System

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

  LandingPageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./functions/landing_page/
      Handler: app.lambda_handler
      Runtime: python3.10
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref ApiGateway

  RecordAndConfirmFeedbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./functions/record_and_confirm_feedback/
      Handler: app.lambda_handler
      Runtime: python3.10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FeedbackTable
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt FeedbackTopic.TopicName
      Environment:
        Variables:
          TABLE_NAME: !Ref FeedbackTable
          TOPIC_ARN: !Ref FeedbackTopic
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /feedback
            Method: post
            RestApiId: !Ref ApiGateway

  FeedbackTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  FeedbackTopic:
    Type: AWS::SNS::Topic

Outputs:
  ApiUrl:
    Description: URL of the API Gateway
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
